-- IPL 2026 Player Seed Data
-- Token values: 13 (elite), 11-12 (star), 9-10 (good), 7-8 (budget)

insert into players (name, ipl_team, role, token_value) values
-- Chennai Super Kings
('MS Dhoni', 'CSK', 'keeper', 12),
('Ruturaj Gaikwad', 'CSK', 'batsman', 11),
('Devon Conway', 'CSK', 'batsman', 10),
('Shivam Dube', 'CSK', 'allrounder', 9),
('Ravindra Jadeja', 'CSK', 'allrounder', 12),
('Deepak Chahar', 'CSK', 'bowler', 9),
('Matheesha Pathirana', 'CSK', 'bowler', 10),
('Moeen Ali', 'CSK', 'allrounder', 9),
('Rachin Ravindra', 'CSK', 'batsman', 9),
('Tushar Deshpande', 'CSK', 'bowler', 8),
('Sameer Rizvi', 'CSK', 'batsman', 8),

-- Mumbai Indians
('Rohit Sharma', 'MI', 'batsman', 13),
('Jasprit Bumrah', 'MI', 'bowler', 13),
('Suryakumar Yadav', 'MI', 'batsman', 13),
('Hardik Pandya', 'MI', 'allrounder', 12),
('Ishan Kishan', 'MI', 'keeper', 10),
('Tim David', 'MI', 'batsman', 10),
('Tilak Varma', 'MI', 'batsman', 9),
('Jofra Archer', 'MI', 'bowler', 11),
('Romario Shepherd', 'MI', 'allrounder', 8),
('Naman Dhir', 'MI', 'batsman', 7),
('Akash Madhwal', 'MI', 'bowler', 8),

-- Royal Challengers Bengaluru
('Virat Kohli', 'RCB', 'batsman', 13),
('Faf du Plessis', 'RCB', 'batsman', 11),
('Glenn Maxwell', 'RCB', 'allrounder', 11),
('Mohammed Siraj', 'RCB', 'bowler', 10),
('Dinesh Karthik', 'RCB', 'keeper', 9),
('Cameron Green', 'RCB', 'allrounder', 10),
('Alzarri Joseph', 'RCB', 'bowler', 9),
('Yash Dayal', 'RCB', 'bowler', 8),
('Anuj Rawat', 'RCB', 'keeper', 7),
('Suyash Prabhudessai', 'RCB', 'batsman', 7),
('Karn Sharma', 'RCB', 'bowler', 8),

-- Kolkata Knight Riders
('Shreyas Iyer', 'KKR', 'batsman', 11),
('Andre Russell', 'KKR', 'allrounder', 12),
('Sunil Narine', 'KKR', 'allrounder', 12),
('Phil Salt', 'KKR', 'keeper', 10),
('Nitish Rana', 'KKR', 'batsman', 9),
('Varun Chakravarthy', 'KKR', 'bowler', 10),
('Mitchell Starc', 'KKR', 'bowler', 11),
('Harshit Rana', 'KKR', 'bowler', 9),
('Rinku Singh', 'KKR', 'batsman', 10),
('Venkatesh Iyer', 'KKR', 'allrounder', 9),
('Angkrish Raghuvanshi', 'KKR', 'batsman', 7),

-- Sunrisers Hyderabad
('Pat Cummins', 'SRH', 'bowler', 12),
('Heinrich Klaasen', 'SRH', 'keeper', 12),
('Travis Head', 'SRH', 'batsman', 12),
('Abhishek Sharma', 'SRH', 'allrounder', 10),
('Bhuvneshwar Kumar', 'SRH', 'bowler', 9),
('T Natarajan', 'SRH', 'bowler', 9),
('Aiden Markram', 'SRH', 'batsman', 10),
('Marco Jansen', 'SRH', 'allrounder', 10),
('Washington Sundar', 'SRH', 'allrounder', 9),
('Mayank Agarwal', 'SRH', 'batsman', 8),
('Shahbaz Ahmed', 'SRH', 'allrounder', 8),

-- Delhi Capitals
('Rishabh Pant', 'DC', 'keeper', 13),
('David Warner', 'DC', 'batsman', 11),
('Axar Patel', 'DC', 'allrounder', 10),
('Anrich Nortje', 'DC', 'bowler', 11),
('Mitchell Marsh', 'DC', 'allrounder', 10),
('Prithvi Shaw', 'DC', 'batsman', 8),
('Kuldeep Yadav', 'DC', 'bowler', 10),
('Tristan Stubbs', 'DC', 'batsman', 9),
('Mukesh Kumar', 'DC', 'bowler', 8),
('Jhye Richardson', 'DC', 'bowler', 9),
('Abishek Porel', 'DC', 'batsman', 7),

-- Punjab Kings
('Shikhar Dhawan', 'PBKS', 'batsman', 10),
('Sam Curran', 'PBKS', 'allrounder', 10),
('Liam Livingstone', 'PBKS', 'allrounder', 10),
('Jonny Bairstow', 'PBKS', 'keeper', 10),
('Arshdeep Singh', 'PBKS', 'bowler', 11),
('Kagiso Rabada', 'PBKS', 'bowler', 11),
('Rilee Rossouw', 'PBKS', 'batsman', 9),
('Nathan Ellis', 'PBKS', 'bowler', 8),
('Harpreet Brar', 'PBKS', 'allrounder', 8),
('Prabhsimran Singh', 'PBKS', 'keeper', 8),
('Harshal Patel', 'PBKS', 'bowler', 9),

-- Rajasthan Royals
('Sanju Samson', 'RR', 'keeper', 12),
('Jos Buttler', 'RR', 'keeper', 12),
('Yashasvi Jaiswal', 'RR', 'batsman', 12),
('Ravichandran Ashwin', 'RR', 'allrounder', 10),
('Trent Boult', 'RR', 'bowler', 11),
('Shimron Hetmyer', 'RR', 'batsman', 9),
('Yuzvendra Chahal', 'RR', 'bowler', 10),
('Dhruv Jurel', 'RR', 'keeper', 8),
('Riyan Parag', 'RR', 'allrounder', 9),
('Sandeep Sharma', 'RR', 'bowler', 8),
('Rovman Powell', 'RR', 'batsman', 9),

-- Gujarat Titans
('Shubman Gill', 'GT', 'batsman', 12),
('Mohammed Shami', 'GT', 'bowler', 11),
('Wriddhiman Saha', 'GT', 'keeper', 8),
('David Miller', 'GT', 'batsman', 10),
('Rashid Khan', 'GT', 'allrounder', 13),
('Vijay Shankar', 'GT', 'allrounder', 8),
('Sai Sudharsan', 'GT', 'batsman', 9),
('Rahul Tewatia', 'GT', 'allrounder', 9),
('Darshan Nalkande', 'GT', 'bowler', 7),
('Umesh Yadav', 'GT', 'bowler', 8),
('Noor Ahmad', 'GT', 'bowler', 9),

-- Lucknow Super Giants
('KL Rahul', 'LSG', 'keeper', 12),
('Nicholas Pooran', 'LSG', 'keeper', 11),
('Quinton de Kock', 'LSG', 'keeper', 11),
('Marcus Stoinis', 'LSG', 'allrounder', 10),
('Krunal Pandya', 'LSG', 'allrounder', 9),
('Ravi Bishnoi', 'LSG', 'bowler', 10),
('Avesh Khan', 'LSG', 'bowler', 9),
('Deepak Hooda', 'LSG', 'allrounder', 8),
('Ayush Badoni', 'LSG', 'batsman', 8),
('Amit Mishra', 'LSG', 'bowler', 7),
('Prerak Mankad', 'LSG', 'allrounder', 7);
